[actions]
"actions/checkout" = "^6"
"actions/create-github-app-token" = "^2"
"actions/download-artifact" = "^6"
"actions/github-script" = "^8"
"actions/setup-node" = "^6"
"actions/upload-artifact" = "^5"
"docker/build-push-action" = "^6"
"docker/login-action" = "^3"
"docker/metadata-action" = "^5"
"docker/scout-action" = "^1"
"docker/setup-buildx-action" = "^3"
"github/codeql-action/upload-sarif" = "^4"
"grafana/github-api-commit-action" = "^1"
"jaxxstorm/action-install-gh-release" = "^2"
"ossf/scorecard-action" = "^2"
"peter-evans/create-pull-request" = "^7"
"peter-evans/dockerhub-description" = "^5"
"plexsystems/container-structure-test-action" = "~0.3.0"

[actions.overrides]
"actions/download-artifact" = [{ workflow = ".github/workflows/build.yml", job = "test_image", step = 2, version = "^4" }, { workflow = ".github/workflows/build.yml", job = "scan_image", step = 0, version = "^4" }, { workflow = ".github/workflows/update_version.yml", job = "validate_config_version", step = 2, version = "~6.0.0" }, { workflow = ".github/workflows/update_version.yml", job = "update_docs_and_create_pr", step = 2, version = "~6.0.0" }, { workflow = ".github/workflows/update_version.yml", job = "update_docs_and_create_pr", step = 3, version = "~6.0.0" }, { workflow = ".github/workflows/update_version.yml", job = "update_android_version", step = 2, version = "~6.0.0" }]
"docker/metadata-action" = [ { workflow = ".github/workflows/ci.yml", job = "test_image", step = 5, version = "~5.10.0" }, { workflow = ".github/workflows/release.yml", job = "release_android", step = 2, version = "~5.10.0" }, { workflow = ".github/workflows/windows.yml", job = "test_windows", step = 3, version = "~5.7.0" }, { workflow = ".github/workflows/windows.yml", job = "test_windows", step = 4, version = "~5.7.0" }, { workflow = ".github/workflows/release.yml", job = "release_windows", step = 2, version = "~5.10.0" }, { workflow = ".github/workflows/build.yml", job = "build_image", step = 7, version = "~5.10.0" }]
"docker/scout-action" = [{ workflow = ".github/workflows/build.yml", job = "scan_image", step = 3, version = "~1.20.4" }, { workflow = ".github/workflows/release.yml", job = "record_image", step = 2, version = "~1.18.2" }, { workflow = ".github/workflows/build.yml", job = "scan_image", step = 4, version = "~1.20.4" }]
