[actions]
"actions/checkout" = "^6"
"actions/create-github-app-token" = "^2"
"actions/download-artifact" = "^6"
"actions/github-script" = "^8"
"actions/upload-artifact" = "^5"
"docker/build-push-action" = "^6"
"docker/login-action" = "^3"
"docker/metadata-action" = "^5"
"docker/scout-action" = "^1"
"docker/setup-buildx-action" = "^3"
"github/codeql-action/upload-sarif" = "^4"
"grafana/github-api-commit-action" = "^1"
"jdx/mise-action" = "^4"
"ossf/scorecard-action" = "^2"
"peter-evans/create-pull-request" = "^7"
"peter-evans/dockerhub-description" = "^5"
"plexsystems/container-structure-test-action" = "~0.3.0"
"step-security/harden-runner" = "^2"
