on:
  push:
    branches:
      - main
    paths:
      - config/version.json
  workflow_dispatch:

jobs:
  changelog:
    runs-on: ubuntu-24.04
    env:
      IMAGE_REPOSITORY_NAME: flutter-android
      VERSION_MANIFEST: config/version.json
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # TODO: Fetch only a few commits after using --unreleased in git-cliff
          # Fetch all commits to use as input for the changelog generation
          fetch-depth: 0
          # Fetch all tags to use as input for the changelog generation
          fetch-tags: true
      
      - name: Setup git-cliff
        uses: jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2 # v2.1.0
        with:
          repo: orhun/git-cliff
          tag: v2.8.0
          digest: 17da092783079c63a0fb14c24fbfa0d3b589e225c6ef01c93111e39cecbc88e8

      - name: Read environment variables from the version manifest
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          IMAGE_REPOSITORY_NAME: ${{ env.IMAGE_REPOSITORY_NAME }}
          VERSION_MANIFEST: ${{ env.VERSION_MANIFEST }}
        with:
          script: |
            const script = require('./script/setEnvironmentVariables.js')
            return await script({ core })
      
      - name: Update changelog
        run: |
          git-cliff -v --tag ${{ env.FLUTTER_VERSION }} --github-repo ${{ github.repository }} --output changelog.md
      
      - name: Generate authentication token with GitHub App to trigger Actions
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        id: app-token
        with:
          app-id: ${{ secrets.VERIFIED_COMMIT_ID }}
          private-key: ${{ secrets.VERIFIED_COMMIT_KEY }}
          repositories: ${{ github.event.repository.name }}
          owner: ${{ github.repository_owner }}

      - name: Commit and push changelog
        uses: grafana/github-api-commit-action@b1d81091e8480dd11fcea8bc1f0ab977a0376ca5 # v1.0.0
        with:
          commit-message: "chore(release): prepare for ${{ env.FLUTTER_VERSION }}"
          stage-all-files: true
          token: ${{ steps.app-token.outputs.token }}
