on:
  pull_request:
    paths:
      - .github/workflows/pr_config.yml
      - config/**
  workflow_dispatch:

jobs:
  test_config:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      
      - name: Setup NodeJS
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          cache: 'npm'
          cache-dependency-path: docs/src/package-lock.json
          node-version-file: docs/src/package.json

      - name: Setup Cue for JSON validation
        uses: cue-lang/setup-cue@1713281ae501e533ff06108005dffeab9e2e5203 # v1.0.0

      - name: Validate version.json and flutter_version.json
        run: |
          cue vet config/version.cue config/version.json
          cue vet config/flutter_version.cue config/flutter_version.json
