on:
  pull_request:
    paths:
      - .github/workflows/pr_config.yml
      - config/**
  workflow_dispatch:

jobs:
  validate_version:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

      - name: Setup Cue for JSON validation
        uses: cue-lang/setup-cue@1713281ae501e533ff06108005dffeab9e2e5203 # v1.0.0

      - name: Validate version.json and flutter_version.json
        run: |
          cue vet config/version.cue config/version.json
          cue vet config/flutter_version.cue config/flutter_version.json
  validate_generated_config:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

      - name: Generate test files
        uses: mikefarah/yq@master
        with:
          cmd: ./script/update_test.sh

      - name: Check if there are any changes in the git working tree
        run: |
          git add -A  
          git diff --exit-code HEAD
