on:
  push:
    branches:
      - main
    paths:
      - docs/src/**
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update_docs:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup mise tools
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1

      - name: Build documentation
        working-directory: docs/src
        run: |
          pnpm install --frozen-lockfile
          pnpm run build

      - name: Generate authentication token with GitHub App to trigger Actions
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: app-token
        with:
          app-id: ${{ secrets.VERIFIED_COMMIT_ID }}
          private-key: ${{ secrets.VERIFIED_COMMIT_KEY }}
          repositories: ${{ github.event.repository.name }}
          owner: ${{ github.repository_owner }}

      - name: Commit and push regenerated documentation
        uses: grafana/github-api-commit-action@b1d81091e8480dd11fcea8bc1f0ab977a0376ca5 # v1.0.0
        with:
          commit-message: 'docs: regenerate documentation files'
          success-if-no-changes: true
          stage-all-files: true
          token: ${{ steps.app-token.outputs.token }}
